server:
  port: 8092

spring:
  application:
    name: notification
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5433/notification
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/