server:
  port: 8091

spring:
  application:
    name: fraud
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5433/fraud
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update