server:
  port: 8091

spring:
  application:
    name: fraud
  datasource:
    username: postgres
    url: jdbc:postgresql://postgres:5432/postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0